name: Generate GitHub Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # runs every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate snake.svg
        uses: platane/snk@v3
        with:
          github_user_name: 'ribhav1'
          outputs: 'dist/snake.svg'

      - name: Show generated file (debug)
        run: |
          echo "Listing dist/"
          ls -la dist || true

      - name: Prepare output branch and push snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          # If an 'output' branch exists, checkout it, else create an orphan branch
          if git show-ref --verify --quiet refs/heads/output; then
            git checkout output
            # Remove tracked files on the output branch to keep it minimal
            git rm -rf . || true
          else
            git checkout --orphan output
          fi

          # Copy the generated svg to the repo root (so URL is /output/snake.svg)
          mkdir -p .
          cp dist/snake.svg snake.svg
          git add snake.svg

          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "chore: update snake"
            git push origin output --force
          fi
